version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: db_logs
    environment:
      POSTGRES_DB: db_logs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      DD_SERVICE: postgres
      DD_ENV: dev
      # Configs para log detalhado
      POSTGRES_LOG_STATEMENT: all
      POSTGRES_LOG_MIN_DURATION_STATEMENT: 500
    ports:
      - "5433:5432"
    volumes:
      - postgres-logs-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logs_api:
    build: .
    container_name: logs-api
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_logs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      DD_SERVICE: logs-api
      DD_ENV: dev
      DD_VERSION: 1.0.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=afbe060e930bfac87dc375d71592f65d
      - DD_SITE=us5.datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_ENV=dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

volumes:
  postgres-logs-data:
